name: "Create Pull Request | jcdcdev"
description: "Creates a GitHub Pull Request with automated changelog"
author: "James Carter"
branding:
  icon: "tag"
  color: "gray-dark"
inputs:
  dry-run:
    description: "Dry run: Run the workflow without creating a Pull Request"
    required: false
    default: false
  source-branch:
    description: "Source branch"
    required: true
  target-branch:
    description: "Target branch"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
outputs:
  pr-number:
    description: "Pull Request Number"
    value: ${{ steps.create-pull-request.outputs.number }}

runs:
  using: "composite"
  steps:
    - name: Set Variables
      shell: bash
      run: |
        echo "Setting variables"
        SOURCE=${{ inputs.source-branch }}
        TARGET=${{ inputs.target-branch }}
        DRY_RUN=${{ contains(inputs.dry-run, 'true') }}

        echo "SOURCE=$SOURCE"
        echo "TARGET=$TARGET"
        echo "DRY_RUN=$DRY_RUN"

        echo "SOURCE=$SOURCE" >> $GITHUB_ENV
        echo "TARGET=$TARGET" >> $GITHUB_ENV
        echo "DRY_RUN=$DRY_RUN" >> $GITHUB_ENV
    - name: Validate
      shell: bash
      run: |
        if [ -z "$SOURCE" ]; then
          echo "SOURCE is empty"
          exit 1
        fi

        if [ -z "$TARGET" ]; then
          echo "TARGET is empty"
          exit 1
        fi

        if [ "$SOURCE" == "$TARGET" ]; then
          echo "SOURCE is the same as TARGET"
          exit 1
        fi
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ env.SOURCE }}
    - name: Check for changes
      shell: bash
      id: check-for-changes        
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      
        git fetch --all
        git checkout ${{ env.TARGET }}

        DIFF_COUNT=$(git diff --name-only ${{ env.TARGET }} ${{ env.SOURCE }} | wc -l)
        if [ $DIFF_COUNT -eq 0 ]; then
          echo "No changes between ${{ env.TARGET }} and ${{ env.SOURCE }}"
          echo "SHOULD_RUN=false" >> $GITHUB_ENV
          exit 
        fi
        
        echo "$DIFF_COUNT files changed between ${{ env.TARGET }} and ${{ env.SOURCE }}"

        DIFF_FILES=$(git diff --name-status ${{ env.TARGET }} ${{ env.SOURCE }})
        
        echo "Files Changed
        
        $DIFF_FILES 
        "

        DIFF_SNIPPET=$(echo "$DIFF_FILES" | awk '
        {
          if ($1 == "A") {
            print "+ " $2
          } else if ($1 == "D") {
            print "- " $2
          } else {
            print "~ " $2
          }
        }')

        echo "DIFF_SNIPPET
        
        $DIFF_SNIPPET
        "

        DIFF_TEXT="## Files Changed```DIFF
        ${DIFF_SNIPPET}
        ```"
        
        echo "DIFF_TEXT

        $DIFF_TEXT
        "

        git merge $SOURCE --no-ff --no-edit

        echo "SHOULD_RUN=true" >> $GITHUB_ENV
        echo 'DIFF_COUNT=$DIFF_COUNT' >> $GITHUB_ENV

        {
          echo 'DIFF_TEXT<<EOF'
          echo "${DIFF_TEXT}"
          echo EOF
        } >> "$GITHUB_ENV"  
    - name: Download GitVersion.yml
      if: ${{ env.SHOULD_RUN == 'true' }}
      shell: bash
      run: curl -sSL https://raw.githubusercontent.com/jcdcdev/jcdcdev.Umbraco.GitHub.Build/main/GitVersion.yml -o GitVersion.yml
    - name: Install GitVersion
      if: ${{ env.SHOULD_RUN == 'true' }}
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: "5.x"
    - name: Determine Version
      if: ${{ env.SHOULD_RUN == 'true' }}
      id: gitversion
      uses: gittools/actions/gitversion/execute@v1.1.1
      with:
        useConfigFile: true
        configFilePath: "GitVersion.yml"
        disableNormalization: true 
    - uses: jcdcdev/jcdcdev.Github.GenerateChangelog@main
      if: ${{ env.SHOULD_RUN == 'true' }}
      id: changelog
      with:
        version: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
        head-ref: ${{ env.TARGET }}
        github-token: ${{ inputs.github-token }}
        include-version-as-heading: true
        include-compare-link: false
        include-links: true
    - name: Set Pull Request Information
      shell: bash
      if: ${{ env.SHOULD_RUN == 'true' }}
      run: |
        TITLE="${{ steps.gitversion.outputs.NuGetVersionV2 }}"
        BODY="${{ steps.changelog.outputs.changelog }}
        ${{ env.DIFF_TEXT }}"
        
        echo "TITLE=$TITLE"
        echo "BODY=$BODY"

        echo "TITLE=$TITLE" >> $GITHUB_ENV
        {
          echo 'BODY<<EOF'
          echo "${BODY}"
          echo EOF
        } >> "$GITHUB_ENV"  
    - name: Create PR
      id: create-pull-request
      if: ${{ env.SHOULD_RUN == 'true' && env.DRY_RUN == 'false' }}
      env:
        SOURCE: ${{ env.SOURCE }}
        TARGET: ${{ env.TARGET }}
        TITLE: ${{ env.TITLE }}
        BODY: ${{ env.BODY}}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: pyrbin/single-pr-updater@latest
      with:
        label: 🚀 release
        head: ${{ env.SOURCE }}
        base: ${{ env.TARGET }}
        title: ${{ env.TITLE }}
        body: ${{ env.BODY }}
        draft: false